name: Miri

on:
  push:
  pull_request:

jobs:
  miri:
    name: Run Miri
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        components: miri
        override: true

    - name: Setup Miri
      run: rustup run nightly cargo miri setup

    - name: Run Miri Tests
      run: cargo +nightly miri test